# Generated by Django 2.2 on 2020-09-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200929_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Faculty'), ('Student', 'Student')], default='Student', max_length=7),
        ),
    ]
