# Generated by Django 2.2 on 2020-09-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.PositiveSmallIntegerField(blank=True, choices=[(27, 'COE-27'), (28, 'COE-28'), (29, 'COE-29'), (30, 'COE-30')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Batch'),
        ),
    ]
