# Generated by Django 2.2 on 2020-09-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0003_entry_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_Name', models.CharField(max_length=100)),
                ('Date_Published', models.DateTimeField(auto_now_add=True)),
                ('Assignment_Content', models.CharField(max_length=10000)),
                ('Batch', models.CharField(choices=[('COE-24', 'COE-24'), ('COE-25', 'COE-25'), ('COE-26', 'COE-26'), ('COE-27', 'COE-27'), ('COE-28', 'COE-28')], default='COE-24', max_length=6)),
                ('Publishing_Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
