# Generated by Django 2.2 on 2020-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200927_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Batch',
            field=models.CharField(choices=[('COE-24', 'COE-24'), ('COE-25', 'COE-25'), ('COE-26', 'COE-26'), ('COE-27', 'COE-27'), ('COE-28', 'COE-28')], max_length=6),
        ),
    ]
