# Generated by Django 2.2 on 2020-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20200927_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assignment_Content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Batch',
            field=models.CharField(max_length=2),
        ),
    ]
