# Generated by Django 2.2 on 2020-09-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20200927_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Batch',
            field=models.CharField(choices=[('24', 'COE-24'), ('25', 'COE-25'), ('26', 'COE-26'), ('27', 'COE-27'), ('28', 'COE-28')], max_length=2),
        ),
    ]
