# Generated by Django 2.2 on 2020-09-27 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20200928_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(choices=[('firstbatch', 'COE-24'), ('secondbatch', 'COE-25'), ('thirdbatch', 'COE-26'), ('fourthbatch', 'COE-27'), ('fifthbatch', 'COE-28')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entries.Batch'),
        ),
    ]
